
spring.data.mongodb.uri=mongodb+srv://dbUser:Hospital@cluster0.dxxypw7.mongodb.net/hospital_db?retryWrites=true&w=majority&appName=Cluster0
# Server Port
server.port=8080

# Error Handling
server.error.include-message=always

